ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPEED_MULTIPLIER = 1.2

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

PROJECTILE_RADIUS = 5

FPS = 60

STATE_MENU = "MENU_STATE"
STATE_PLAYING = "PLAYING_STATE"
STATE_GAME_OVER = "GAME_OVER_STATE"

# TODO Add colors
# Primary, Secondary, Tertiary
# Player, Bullets, Asteroids